[package]
name = "ai"
version = "0.1.0"
edition = "2021"

[dependencies]
env = { path = "../env" }
revonet = { path = "../../revonet" }
rand = "0.8.5"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.2"